
build:
	cd farmhub && make biothings_farmhub
	cd elastic && make elastic_farm
	cd rproxy && make rproxy_farm

save:
	cd farmhub && make biothings_farmhub save
	cd elastic && make elastic_farm save
	cd rproxy && make rproxy_farm save

sends3:
	cd farmhub && make biothings_farmhub sends3
	cd elastic && make elastic_farm sends3
	cd rproxy && make rproxy_farm sends3
